version: '3'

services:
  db:
    container_name: diverse-db-development
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_cache:/var/lib/mysql:cached
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=diverse_development

  redis:
    container_name: diverse-redis-development
    image: 'redis:6-alpine'
    command: redis-server
    volumes:
      - redis_data:/data

  web:
    container_name: diverse-web-development
    build:
      context: ../..
      dockerfile: deployments/development/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ../..:/app
      - bundle_cache:/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  sidekiq:
    container_name: diverse-sidekiq-development
    build:
      context: ../..
      dockerfile: deployments/development/Dockerfile
    command: bundle exec sidekiq
    volumes:
      - ../..:/app
      - bundle_cache:/bundle
      - node_modules:/app/node_modules
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

networks:
  default:
    name: diverse-development

volumes:
  db_cache:
  bundle_cache:
  node_modules:
  redis_data:
